### ISSUE TITLE
Blockly touch events can get handled twice (ghost clicks)

### ISSUE THREAD

**Issue by Adam13531** [Adam13531/BotLand#192] opened 2018-04-24 19:14 UTC
**Steps to reproduce**
1. Make sure you load Blockly either in mobile-emulation mode or a real mobile device so that you have proper touch-event handling.
2. Drag a block with a dropdown (like `move`) onto the canvas.
3. Open the dropdown in such a way that the options appear on top of another element somewhere in the header.
4. Tap an option from the dropdown that is over another control in the header somewhere. For example, the word `down` in the screenshot below is over the script library control:
![image](https://user-images.githubusercontent.com/7192897/39208688-94d4cdfc-47b8-11e8-9dbd-4d85ec1933f8.png)

**Expected outcome**
The tap only works in Blockly and then stops completely.

**Actual outcome**
The tap continues (probably as a click event) *beyond* Blockly and goes to the control behind the dropdown.

I'm filing this bug in Bot Land because it repros there, but I think that this is caused by a Blockly issue: https://github.com/Microsoft/pxt-blockly/pull/96

I think the issue is fixed thanks to [this pull request](https://github.com/google/blockly/pull/1614), but it still repros on one of [the official online sample pages](https://blockly-demo.appspot.com/static/demos/code/index.html) as of today.

**Comment by Skedog** [comment] 2018-10-02 19:06
I cannot reproduce this in Bot land at this time, so I am closing this. Feel free to re-open if you run into this in the future.

**Closed by Skedog** 2018-10-02 19:06 UTC
Labels: bug
