### ISSUE TITLE
Stuck in tutorial after winning against AI

### ISSUE THREAD

**Issue by freaktechnik** [Adam13531/BotLand#253] opened 2018-09-06 11:27 UTC
**Steps to reproduce**
- Start attack tutorial
- Beat AI
- Minimize results screen

**Expected outcome**
Can close the match and go back to start screen

**Actual outcome**
Clicking the close button opens a dialog saying you can't do that during the tutorial, but the button to bring back up the attack sceen is also missing, so you're now stuck there for all eternity

**Browser (and version)**
{"name":"Firefox","firefox":true,"version":"64.0","gecko":true,"linux":true,"a":true}

**In-game information**
Client version: 0.2.48
Player ID: 25
Player name: freaktechnik

**Comment by Adam13531** [comment] 2018-09-07 19:00
I'm pretty sure this is a duplicate of #255 in that you aren't supposed to even attack at all during the Attack Introduction tutorial. Please reopen if that's not the case.

**Closed by Adam13531** 2018-09-07 19:00 UTC
Labels: bug
