### ISSUE TITLE
Store purchase/sell confirmation modals appear behind the store

### ISSUE THREAD

**Issue by judgebacon** [Adam13531/BotLand#94] opened 2017-09-27 01:01 UTC
**Steps to reproduce**
1. Open the store
2. Click "Buy" or "Sell" on an item

**Expected outcome**
The purchase and selling confirmation modals to appear in front of the store so I can click "Purchase", "Sell", or "Cancel".

**Actual outcome**
The purchase and selling confirmation modals appears behind the store. I have to close the store UI to interact with said modal.

**Browser (and version)**
Chrome version 60.0.3112.113 (Official Build) (64-bit)

**Operating system (and version)**
Windows 10 version 1703

**Extra info**
Screen resolution: 1600x900

**Comment by judgebacon** [comment] 2017-09-27 01:09
Same thing occurs when you attempt to buy a pack. Not sure if it is the case for opening; I do not have any to test with.

**Comment by HiDeoo** [comment] 2017-09-27 02:55
Can confirm, this is a `z-index` issue on the `ReactModal__Overlay` class.

I'm gonna bet this is a regression due to the refactor @Adam13531 did to all the z-index in the whole app. At the moment, this class is getting a `z-index` of `72` while the store modal is getting a `z-index` of `75`.

**Comment by Adam13531** [comment] 2017-09-27 16:31
@judgebacon and I talked about this on Discord; @HiDeoo is correct. I'd done all this work around `z-index`es without ever applying that solution to modal dialogs.

This is fixed in version 0.1.69.

**Closed by Adam13531** 2017-09-27 16:31 UTC
