### ISSUE TITLE
'Prettify code' button dont work

### ISSUE THREAD

**Issue by Matlino** [Adam13531/BotLand#170] opened 2018-02-28 21:30 UTC
**Steps to reproduce**
convert script to JS, cant go back with prettify code button
**Expected outcome**
prettify code
**Actual outcome**
nothing happen
**Browser information**
{"name":"Chrome","chrome":true,"version":"64.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 1140
Player name: matlo

**Comment by HiDeoo** [comment] 2018-02-28 21:53
Are you expecting to see Blockly blocks when clicking *Prettify*?

Even if placed at the same place as the *Convert to JS* button, the *Prettify code* button doesn't convert JS code to Blockly (which is impossible in Bot Land at the moment and will probably never be). It'll simply "prettify" (remove extra spaces, invalid indentations, etc.) from your JS code.

For example, having as code:

```js
update = function () { if (canMove()) { move(); }};
```

Using *Prettify* would give the following code:

```js
update = function () {
    if (canMove()) {
        move();
    }
};
```

Altho, if your code is already prettified, you might not notice any change at the moment as the operation completion is not indicated in any way. Maybe it should be with an icon in a status bar in like most text editor or a totally different button, or a button at a different place than the *Convert to Blockly* one, have a tooltip or use a different wording.

**Note:** Duplicate of #124

**Comment by Matlino** [comment] 2018-02-28 22:05
Yes i was expecting going back to blockly. Now i see, my expectation was wrong :D yes its little bit confusing because its same color and same place as 'convert to JS' button. But its nothing critical :)

**Comment by Adam13531** [comment] 2018-05-01 20:17
Closing since this is a duplicate of #124 and I recently commented on that bug.

**Closed by Adam13531** 2018-05-01 20:17 UTC
Labels: duplicate, enhancement, needs investigation
