### ISSUE TITLE
GameScreen Zooms the UI out of screen

### ISSUE THREAD

**Issue by ageddesi** [Adam13531/BotLand#101] opened 2017-10-16 18:47 UTC
Not sure if this is a bug or just a quirk of zooming.

**Steps to reproduce**
go to the edit defence screen.
zoom in on the play area.
if you go to a certain threshold the ui is thrown out of the page and replaced with complete play screen.

**Expected outcome**
UI to stay where it is no matter zoom level. 

**Actual outcome**

**Bowser information**
{"name":"Chrome","chrome":true,"version":"61.0","blink":true,"mac":true,"a":true}

**In-game information**
Player ID: 1283
Player name: sirrackley
<img width="1919" alt="screen shot 2017-10-16 at 19 45 29" src="https://user-images.githubusercontent.com/1301564/31629212-dd6c5c18-b2aa-11e7-8253-782a997d87c4.png">
<img width="1916" alt="screen shot 2017-10-16 at 19 45 37" src="https://user-images.githubusercontent.com/1301564/31629213-dd989b5c-b2aa-11e7-9254-593693fca666.png">

**Comment by Adam13531** [comment] 2017-10-25 03:23
@ageddesi hey, I can't figure out how you got this to happen. :( I'm assuming you're just using the in-game zoom (as opposed to the browser zoom with cmd+plus), but I can't reproduce this.

Are you zooming using a gesture (e.g. a trackpad on a MacBook) or a mouse?

**Comment by ageddesi** [comment] 2017-10-25 07:31
I am indeed using it on a trackpad on the Mac laptop.
I will have a try later with just my mouse attached and see if that makes a difference sir @Adam13531

**Comment by ageddesi** [comment] 2017-10-25 07:56
Hi @Adam13531 I confirmed that if I use my mouse it is fine, the trackpad zooming is what causing the issue, Will leave this open so you can decide if it is something worth fixing.

**Comment by HiDeoo** [comment] 2017-10-25 08:01
I would expect most Mac users having a trackpad (which can happens on portable but also desktop with Magic Trackpad) to actually try to zoom using a pinch gesture.

As Hammer.js actually supports it, it may be worth just having the same behavior for pinch & wheel.

**Comment by Adam13531** [comment] 2017-10-25 16:33
This entire comment is just a note to myself.

- I *do* have a pinch handler and it is probably buggy.
- Chrome does allow you to test this with Device Mode by holding shift and dragging the mouse, but I have it disabled apparently via my `meta` tag in my `index.pug` (although I couldn't seem to disable it in testing quickly).

**Comment by Adam13531** [comment] 2019-06-07 19:15
As of February, 2019, it *seems* like this has been fixed, so I'm going to close it.

**Closed by Adam13531** 2019-06-07 19:15 UTC
Labels: bug
