### ISSUE TITLE
[MOBILE] Unreachable buttons in replay screen

### ISSUE THREAD

**Issue by Pnoexz** [Adam13531/BotLand#174] opened 2018-04-02 18:49 UTC
**Steps to reproduce**
* Log in
* View replay from attack log (only screen I tested so far)

**Expected outcome**
Buttons on bottom bar are visible and clickable

**Actual outcome**
Can see the top of the buttons, but no bar. They are clickable though, but can't pick phases.

It makes no difference if you are on portrait mode or not; even if you switch once it's already on that screen. Trying to scroll down moves the camera around the arena.

![screenshot_20180402-153328](https://user-images.githubusercontent.com/3297901/38210248-62bf943c-36a6-11e8-8d0b-ae2776b8965c.png)
![screenshot_20180402-154325](https://user-images.githubusercontent.com/3297901/38210250-63023abc-36a6-11e8-8245-e851152c20dd.png)

**Browser information**
{"name":"Chrome","chrome":true,"version":"64.0","blink":true,"android":true,"osversion":"7.0","mobile":true,"a":true}

**In-game information**
Player ID: 1090
Player name: Pnoexz

**Comment by Skedog** [comment] 2018-10-02 18:55
Mobile UI has changed quite a bit since this was filed, and I cannot reproduce it anymore. Closing for now, feel free to re-open if you come across this in the future.

**Closed by Skedog** 2018-10-02 18:55 UTC
Labels: bug
