### ISSUE TITLE
Game plays a pop-like sound whilst being completely muted

### ISSUE THREAD

**Issue by Wauteurz** [Adam13531/BotLand#159] opened 2017-11-20 20:16 UTC
**Steps to reproduce**
The bug can be found by turning off the master sound (slider at 0%, box not ticked), arena, music and interface sounds at about 20, 25 and 30% respectively, all of them ticked on.
[Screenshot of settings](https://i.imgur.com/4I1CJAq.png)

**Expected outcome**
The game is silent and does not produce any form of sound.

**Actual outcome**
The game will sound a pop-like sound, silent enough to not be noticed immediately, but annoying enough to be bothersome. The sound will (as was my case) be heard towards the end or shortly after the end of a match, which comes down to roughly once every minute or two. The sound cannot be heard when the game is idle on the title screen with the settings menu open, which is the case while typing this.

**Browser (and version)**
Google Chrome, 64-bit, V 62.0.3202.94

**Operating system (and version)**
Windows 10 Home, 64-bit, Version 1703, Build 15063.726

**Comment by Adam13531** [comment] 2017-11-20 20:17
Just including the screenshot directly:
![image](https://user-images.githubusercontent.com/7192897/33039411-b7e9b906-cdec-11e7-8104-56a49577c584.png)

**Comment by Adam13531** [comment] 2018-05-01 20:12
Closing since this is a duplicate of #96.

**Closed by Adam13531** 2018-05-01 20:12 UTC
Labels: bug
