### ISSUE TITLE
Uncaught AssertionErrors attempting to reproduce issue #96 

### ISSUE THREAD

**Issue by judgebacon** [Adam13531/BotLand#97] opened 2017-09-27 03:52 UTC
Whilst spam clicking around the replay controls attempting to reproduce #96 I opened the Google Chrome console to see if there were any errors

**Steps to reproduce**
This is very hard to reproduce reliably, however I found when spam clicking around the replay system (phase 1) controls I managed to get an almost endless stream of uncaught assert.AssertionError 

_(apologies for not being able to give a reliable method to reproduce this)_

**Expected outcome**
No errors...?

**Actual outcome**
![2017-09-27_04-05-09 - copy](https://user-images.githubusercontent.com/32315725/30894864-48854db0-a33e-11e7-883b-da0e54b78d19.gif)
![chrome_2017-09-27_04-06-05 - copy](https://user-images.githubusercontent.com/32315725/30894847-2ef40d5a-a33e-11e7-8598-2501fd5a7ef1.png)

Stack trace of the errors above:
```js
vendor.min.js:18 Playing 3600: ARTILLERY_IMPACT
vendor.min.js:13 Uncaught assert.AssertionError {name: "AssertionError", actual: false, expected: true, operator: "==", message: "An entity (realId=14) was not found: artilleryLanded - shellEntity", …}
fail @ vendor.min.js:13
ok @ vendor.min.js:13
value @ bundle.min.js:1488
value @ bundle.min.js:1443
value @ vendor.min.js:77
value @ bundle.min.js:1477
value @ bundle.min.js:1444
(anonymous) @ bundle.min.js:1444
setInterval (async)
(anonymous) @ bundle.min.js:1444
value @ bundle.min.js:1444
value @ bundle.min.js:1473
value @ bundle.min.js:1454
onClick @ bundle.min.js:1454
invokeGuardedCallback @ vendor.min.js:53
executeDispatch @ vendor.min.js:52
executeDispatchesInOrder @ vendor.min.js:52
executeDispatchesAndRelease @ vendor.min.js:36
executeDispatchesAndReleaseTopLevel @ vendor.min.js:36
forEachAccumulated @ vendor.min.js:71
processEventQueue @ vendor.min.js:36
runEventQueueInBatch @ vendor.min.js:147
handleTopLevel @ vendor.min.js:147
handleTopLevelImpl @ vendor.min.js:147
perform @ vendor.min.js:45
batchedUpdates @ vendor.min.js:147
batchedUpdates @ vendor.min.js:16
dispatchEvent @ vendor.min.js:147
```

**Browser (and version)**
Chrome version 60.0.3112.113 (Official Build) (64-bit)

**Operating system (and version)**
Windows 10 version 1703

**Comment by judgebacon** [comment] 2017-09-27 03:58
I also found the following in the console at one point, but was not able to reproduce again:

![chrome_2017-09-27_04-09-45 - copy](https://user-images.githubusercontent.com/32315725/30895186-66bd1db0-a340-11e7-98a6-bc4e6898d91d.png)

**Comment by Adam13531** [comment] 2017-09-27 04:29
Closing this as I'm pretty sure it's a duplicate of #68. Let me know if you think that's not the case.

**Closed by Adam13531** 2017-09-27 04:29 UTC
