### ISSUE TITLE
"New script" gets the wrong text after canceling out of the duplication flow

### ISSUE THREAD

**Issue by Adam13531** [Adam13531/BotLand#106] opened 2017-10-23 18:56 UTC
**Steps to reproduce**
1. Edit your defense. Make sure you have a blueprint that doesn't have a script assigned to it.
2. Edit that blueprint.
3. Click "new script"
4. Select an existing script from the script dropdown.
5. Make changes to the script.
6. Click "duplicate"
7. Click "cancel" in the "do you want to save the original script" dialog.
8. Click "cancel" so that you don't save the changes you made earlier

**Expected outcome**
The button next to the assigned script (which will be null since you canceled) on the Edit Blueprint page should say "New script" since you don't have one assigned.

**Actual outcome**
It says "Edit script".

![image](https://user-images.githubusercontent.com/7192897/31907625-391c70e6-b7e9-11e7-8983-fc1d38e34178.png)

**Bowser information**
{"name":"Chrome","chrome":true,"version":"61.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 1
Player name: Adam

**Additional information**
This seems to just be a text problem; clicking the button will still make a new script.

**Comment by Skedog** [comment] 2018-10-01 23:16
Going to close this because this no longer is reproducible as the "button next to the assigned script" no longer exists in the UI.

**Closed by Skedog** 2018-10-01 23:16 UTC
Labels: bug
