### ISSUE TITLE
Can't scroll when viewing cosmetics and hardware in store 

### ISSUE THREAD

**Issue by riversandrew36** [Adam13531/BotLand#32] opened 2017-02-01 00:02 UTC
**Steps to reproduce**
Worked well on chrome for macOS

**Expected outcome**
to be able to scroll for different items 
**Actual outcome**
can't scroll 

**Bowser information**
{"name":"Safari","safari":true,"version":"10.0","webkit":true,"mac":true,"a":true}

**In-game information**
Player ID: 108
Player name: hitchslap11

**Comment by HiDeoo** [comment] 2017-02-01 00:03
Duplicate of #27.

**Closed by HiDeoo** 2017-02-01 00:03 UTC

**Comment by riversandrew36** [comment] 2017-02-01 00:16
Thanks HiDeoo 👍
