### ISSUE TITLE
Store moves down offscreen

### ISSUE THREAD

**Issue by DennisRas** [Adam13531/BotLand#280] opened 2018-10-31 17:27 UTC
I'm not 100% sure when the bug happens, but these are all of the steps I did.
I assume it's the replay that bugs the UI.

**Steps to reproduce**
- Attack and finish a game (winning is optional - Hi Adam!)
- Hide the results
- Click phase 1 to watch the replay
- Exit the replay
- Open the store

**Expected outcome**
Regular store view

**Actual outcome**
Store is moved down.
Note that the screenshot below is **not** cropped.

![](https://i.imgur.com/9kycOA2.png)

**Browser information**
{"name":"Chrome","chrome":true,"version":"70.0","blink":true,"windows":true,"a":true}

**In-game information**
Client version: 0.2.54
Player ID: 5
Player name: Liquidor2

**Comment by freaktechnik** [comment] 2018-10-31 17:44
This is a duplicate of #279

**Closed by freaktechnik** 2018-10-31 17:44 UTC

**Comment by DennisRas** [comment] 2018-10-31 23:48
@freaktechnik This issue was created because searching shows nothing since the other issue is closed. Shouldn't the issues remain open until the issue has been released/fixed in the live version? :) Otherwise duplicates happen.

**Comment by freaktechnik** [comment] 2018-11-01 01:00
¯\_(ツ)_/¯ usually deploys happen fairly often, but when Adam is revamping how they work there may be a little gap, but also not my problem... Personally I think duplicates are just fine. You'd rather want the issue to be reported multiple times than never.
