### ISSUE TITLE
Replay doesn't work after losing an attack

### ISSUE THREAD

**Issue by DennisRas** [Adam13531/BotLand#45] opened 2017-02-14 17:57 UTC
**Steps to reproduce**
- Start a new attack
- Lose the attack entirely
- Click "Replay"

**Expected outcome**
- Watch the replay as usual

**Actual outcome**
- The window stays open and nothing happens
- An error is reported in the console

![](http://i.imgur.com/j1mVYNO.png)
![](http://i.imgur.com/E5fc0fp.png)

**The Stack** (Links truncated)

> "AssertionError: Forgot to define a serialize function for the "display_fire" component.
    at DisplayFireComponent.serialize (http://.../0.1.7_.../bundle.min.js:441:7328)
    at Entity.serialize (http://.../0.1.7_.../bundle.min.js:473:25906)
    at Arena.getAllSerializedEntities (http://.../0.1.7_.../bundle.min.js:611:7302)
    at Main.enterReplayModeAsAttacker (http://.../0.1.7_.../bundle.min.js:439:21493)
    at Object.invokeGuardedCallback (http://.../0.1.7_.../bundle.min.js:513:893)
    at executeDispatch (http://.../0.1.7_.../bundle.min.js:512:25324)
    at Object.executeDispatchesInOrder (http://.../0.1.7_.../bundle.min.js:512:25796)
    at executeDispatchesAndRelease (http://.../0.1.7_.../bundle.min.js:492:14572)
    at executeDispatchesAndReleaseTopLevel (http://.../0.1.7_.../bundle.min.js:492:14830)
    at Array.forEach (native)
    at forEachAccumulated (http://.../0.1.7_.../bundle.min.js:566:26080)
    at Object.processEventQueue (http://.../0.1.7_.../bundle.min.js:492:17954)
    at runEventQueueInBatch (http://.../0.1.7_.../bundle.min.js:650:20763)
    at Object.handleTopLevel [as _handleTopLevel] (http://.../0.1.7_.../bundle.min.js:650:20990)
    at handleTopLevelImpl (http://.../0.1.7_.../bundle.min.js:650:22485)
    at ReactDefaultBatchingStrategyTransaction.perform (http://.../0.1.7_.../bundle.min.js:509:7279)"

**Bowser information**
{"name":"Chrome","chrome":true,"version":"56.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 18
Player name: Liquidor

**Comment by DennisRas** [comment] 2017-03-29 16:34
This still doesn't work with all the new changes to Replays and related UI.  
The bug happens if you use a hardware with a fire component.

**Comment by DennisRas** [comment] 2017-03-29 16:35
Screenshot of the bug still happening in the new UI: 

![](http://i.imgur.com/TyfOtK8.png)

**Comment by Adam13531** [comment] 2017-03-29 19:53
Note: I've fixed the original bug (the fix will be present after version 0.1.22). The next bug you mentioned involving DisplayFireComponent is technically different, but I'll leave this issue open so that I can still handle that.

**Comment by Skedog** [comment] 2018-10-01 22:53
I cannot reproduce the first bug, replays seem to work after a loss.

Also, I cannot reproduce the "fire" related assertionError, so I am closing this for now, feel free to re-open if it happens again.

**Closed by Skedog** 2018-10-01 22:53 UTC
Labels: bug
