### ISSUE TITLE
Says I have been defeated even though I "won"

### ISSUE THREAD

**Issue by NilsIrl** [Adam13531/BotLand#228] opened 2018-05-30 20:45 UTC
**Steps to reproduce**

Be offline I guess ?
When someone attacks me basically.

Note (to be read at the end): the one time I was attacked while online it said I won.
Once (1st attack ever) it said I got defeated but still got def skill increased.

**Expected outcome**

A message in the battle log saying I "won".

e.g.: `x's attack was thwarted`

**Actual outcome**

`x defeated your defence`
and I loose def skill (except for once I got def skill)

**Browser information**
{"name":"Firefox","firefox":true,"version":"60.0","gecko":true,"linux":true,"a":true}

**In-game information**
Client version: 0.2.27
Player ID: 2071
Player name: geophertz

**Comment by freaktechnik** [comment] 2018-05-30 20:48
The rating issues are tracked at https://github.com/Adam13531/BotLand/issues/154 and https://github.com/Adam13531/BotLand/issues/162

Or is the battle log note not correlating with your CPU being destroyed in the match?

Closing as duplicate of #154

**Closed by freaktechnik** 2018-05-30 20:48 UTC

**Comment by NilsIrl** [comment] 2018-05-30 20:56
The battle log is not correlated with my CPU being destroyed.

Also it happens when I get attacked not when I attack.

**Comment by HiDeoo** [comment] 2018-05-30 20:58
Removing as a duplicate at the moment as it was confirmed on stream that there is another issue on top of the ranking going down.

Investigations are required but not possible right now.

**Comment by NilsIrl** [comment] 2018-05-30 20:59
SORRY. I didn't see the second phase of attack !!!!!!!!!!!!!!!!!!!!!

SO I was wrong in the first place.

**Comment by HiDeoo** [comment] 2018-05-30 21:04
To add a little bit on that experience from what Adam said on stream, the replay UI is not polished yet and even complete feature wise, we should have more indicators regarding the different phases and the *play* button should automatically play the next phase.
