### ISSUE TITLE
Not more possible to play any matches

### ISSUE THREAD

**Issue by GELight** [Adam13531/BotLand#166] opened 2017-12-17 12:12 UTC
**Steps to reproduce**
1. Created an account
2. Not activated my account per email link because the email was in spam and there was no information about a needed activation after account creation.
3. Loged in into my account.
4. Played 2 or 3 matches vs another player ( after tutorial steps ).
5. Loosed my 3 attack to another player.
6. Clicked on the "Attack" button in the page "Attack missions" to play more matches.

**Expected outcome**
- Match will be started again ...

**Actual outcome**
- An error is occurred: 

`Error: Unknown error Unexpected token o in JSON at position 1`

- No more possible to play any matches.

** Information about the REST requests**
- https://acct.bot.land/matchmaking > Status 200
- Console info displayed:
- `
The SSL certificate used to load resources from https://d3dby02bhz36nw.cloudfront.net will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
vendor.min.2.js:21 Warning: a promise was created in a handler but was not returned from it
    at <anonymous>
From previous event:
    at Request.Request.endAsync (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:146:11337)
    at Request.Request.then (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:146:11673)
    at AccountServerRestClient.value (https://d3dby02bhz36nw.cloudfront.net/assets/bundle.min.4.js:1562:20975)
    at Main.value (https://d3dby02bhz36nw.cloudfront.net/assets/bundle.min.4.js:1537:20098)
    at Main.throttledFetchBattleLog._.throttle.trailing (https://d3dby02bhz36nw.cloudfront.net/assets/bundle.min.4.js:1535:29242)
    at invokeFunc (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:6:7605)
    at leadingEdge (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:6:7725)
    at Main.debounced [as throttledFetchBattleLog] (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:6:8805)
    at Main.value (https://d3dby02bhz36nw.cloudfront.net/assets/bundle.min.4.js:1537:19403)
    at https://d3dby02bhz36nw.cloudfront.net/assets/bundle.min.4.js:1538:4891
    at Array.<anonymous> (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:137:2023)
    at dispatch (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:60:5990)
    at https://d3dby02bhz36nw.cloudfront.net/assets/bundle.min.4.js:1585:21809
    at https://d3dby02bhz36nw.cloudfront.net/assets/bundle.min.4.js:1585:24378
    at https://d3dby02bhz36nw.cloudfront.net/assets/bundle.min.4.js:1585:26590
    at https://d3dby02bhz36nw.cloudfront.net/assets/bundle.min.4.js:1585:26242
    at https://d3dby02bhz36nw.cloudfront.net/assets/bundle.min.4.js:1585:25878
    at https://d3dby02bhz36nw.cloudfront.net/assets/bundle.min.4.js:1585:25539
    at https://d3dby02bhz36nw.cloudfront.net/assets/bundle.min.4.js:1585:25145
    at https://d3dby02bhz36nw.cloudfront.net/assets/bundle.min.4.js:1585:24759
    at https://d3dby02bhz36nw.cloudfront.net/assets/bundle.min.4.js:1585:24069
    at https://d3dby02bhz36nw.cloudfront.net/assets/bundle.min.4.js:1585:23703
    at https://d3dby02bhz36nw.cloudfront.net/assets/bundle.min.4.js:1585:23362
    at https://d3dby02bhz36nw.cloudfront.net/assets/bundle.min.4.js:1585:23001
    at https://d3dby02bhz36nw.cloudfront.net/assets/bundle.min.4.js:1585:22658
From previous event:
    at Avatar.value (https://d3dby02bhz36nw.cloudfront.net/assets/bundle.min.4.js:1579:31889)
    at onClick (https://d3dby02bhz36nw.cloudfront.net/assets/bundle.min.4.js:1580:1568)
    at Object.invokeGuardedCallback (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:37:29862)
    at executeDispatch (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:37:23152)
    at Object.executeDispatchesInOrder (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:37:23570)
    at executeDispatchesAndRelease (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:31:22305)
    at executeDispatchesAndReleaseTopLevel (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:31:22550)
    at Array.forEach (<anonymous>)
    at forEachAccumulated (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:56:22071)
    at Object.processEventQueue (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:31:24994)
    at runEventQueueInBatch (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:134:13989)
    at Object.handleTopLevel [as _handleTopLevel] (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:134:14158)
    at handleTopLevelImpl (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:134:15133)
    at ReactDefaultBatchingStrategyTransaction.perform (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:34:6297)
    at Object.batchedUpdates (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:134:11203)
    at Object.batchedUpdates (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:13:4277)
    at dispatchEvent (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:134:16905)
`

- Console Error displayed:
- `
Error in receivedOpponentDetailsForJoiningGame SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at https://d3dby02bhz36nw.cloudfront.net/assets/bundle.min.4.js:1537:355
From previous event:
    at Main.value (https://d3dby02bhz36nw.cloudfront.net/assets/bundle.min.4.js:1536:30789)
    at https://d3dby02bhz36nw.cloudfront.net/assets/bundle.min.4.js:1536:30077
    at <anonymous>
From previous event:
    at Main.value (https://d3dby02bhz36nw.cloudfront.net/assets/bundle.min.4.js:1536:30028)
    at https://d3dby02bhz36nw.cloudfront.net/assets/bundle.min.4.js:1593:13187
    at https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:145:3864
    at Object.joinGame (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:145:5214)
    at AttackChoice.value (https://d3dby02bhz36nw.cloudfront.net/assets/bundle.min.4.js:1579:24730)
    at onClick (https://d3dby02bhz36nw.cloudfront.net/assets/bundle.min.4.js:1579:26317)
    at Object.invokeGuardedCallback (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:37:29862)
    at executeDispatch (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:37:23152)
    at Object.executeDispatchesInOrder (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:37:23570)
    at executeDispatchesAndRelease (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:31:22305)
    at executeDispatchesAndReleaseTopLevel (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:31:22550)
    at Array.forEach (<anonymous>)
    at forEachAccumulated (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:56:22071)
    at Object.processEventQueue (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:31:24994)
    at runEventQueueInBatch (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:134:13989)
    at Object.handleTopLevel [as _handleTopLevel] (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:134:14158)
    at handleTopLevelImpl (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:134:15133)
    at ReactDefaultBatchingStrategyTransaction.perform (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:34:6297)
    at Object.batchedUpdates (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:134:11203)
    at Object.batchedUpdates (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:13:4277)
    at dispatchEvent (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:134:16905)
error @ bundle.min.4.js:1572
(anonymous) @ bundle.min.4.js:1537
tryCatcher @ vendor.min.2.js:23
Promise._settlePromiseFromHandler @ vendor.min.2.js:22
Promise._settlePromise @ vendor.min.2.js:22
Promise._settlePromise0 @ vendor.min.2.js:22
Promise._settlePromises @ vendor.min.2.js:22
(anonymous) @ vendor.min.2.js:20
bundle.min.4.js:1572 Error in receivedOpponentDetailsForJoiningGame SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at https://d3dby02bhz36nw.cloudfront.net/assets/bundle.min.4.js:1537:355
From previous event:
    at Main.value (https://d3dby02bhz36nw.cloudfront.net/assets/bundle.min.4.js:1536:30789)
    at https://d3dby02bhz36nw.cloudfront.net/assets/bundle.min.4.js:1536:30077
    at <anonymous>
From previous event:
    at Main.value (https://d3dby02bhz36nw.cloudfront.net/assets/bundle.min.4.js:1536:30028)
    at https://d3dby02bhz36nw.cloudfront.net/assets/bundle.min.4.js:1593:13187
    at https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:145:3864
    at Object.joinGame (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:145:5214)
    at AttackChoice.value (https://d3dby02bhz36nw.cloudfront.net/assets/bundle.min.4.js:1579:24730)
    at onClick (https://d3dby02bhz36nw.cloudfront.net/assets/bundle.min.4.js:1579:26317)
    at Object.invokeGuardedCallback (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:37:29862)
    at executeDispatch (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:37:23152)
    at Object.executeDispatchesInOrder (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:37:23570)
    at executeDispatchesAndRelease (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:31:22305)
    at executeDispatchesAndReleaseTopLevel (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:31:22550)
    at Array.forEach (<anonymous>)
    at forEachAccumulated (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:56:22071)
    at Object.processEventQueue (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:31:24994)
    at runEventQueueInBatch (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:134:13989)
    at Object.handleTopLevel [as _handleTopLevel] (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:134:14158)
    at handleTopLevelImpl (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:134:15133)
    at ReactDefaultBatchingStrategyTransaction.perform (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:34:6297)
    at Object.batchedUpdates (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:134:11203)
    at Object.batchedUpdates (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:13:4277)
    at dispatchEvent (https://d3dby02bhz36nw.cloudfront.net/assets/vendor.min.2.js:134:16905)
error @ bundle.min.4.js:1572
(anonymous) @ bundle.min.4.js:1537
tryCatcher @ vendor.min.2.js:23
Promise._settlePromiseFromHandler @ vendor.min.2.js:22
Promise._settlePromise @ vendor.min.2.js:22
Promise._settlePromise0 @ vendor.min.2.js:22
Promise._settlePromises @ vendor.min.2.js:22
(anonymous) @ vendor.min.2.js:20
Async Call
schedule @ vendor.min.2.js:23
util.hasDevTools.Async.settlePromises @ vendor.min.2.js:20
Promise._reject @ vendor.min.2.js:22
Promise._rejectCallback @ vendor.min.2.js:22
Promise._settlePromiseFromHandler @ vendor.min.2.js:22
Promise._settlePromise @ vendor.min.2.js:22
Promise._settlePromiseCtx @ vendor.min.2.js:22
(anonymous) @ vendor.min.2.js:20
Async Call
schedule @ vendor.min.2.js:23
util.hasDevTools.Async.invoke @ vendor.min.2.js:20
Promise._then @ vendor.min.2.js:22
Promise.then @ vendor.min.2.js:22
value @ bundle.min.4.js:1536
(anonymous) @ bundle.min.4.js:1536
tryCatcher @ vendor.min.2.js:23
Promise._settlePromiseFromHandler @ vendor.min.2.js:22
Promise._settlePromise @ vendor.min.2.js:22
Promise._settlePromise0 @ vendor.min.2.js:22
Promise._settlePromises @ vendor.min.2.js:22
(anonymous) @ vendor.min.2.js:20
Async Call
schedule @ vendor.min.2.js:23
util.hasDevTools.Async.settlePromises @ vendor.min.2.js:20
Promise._fulfill @ vendor.min.2.js:22
Promise._settlePromise @ vendor.min.2.js:22
Promise._settlePromise0 @ vendor.min.2.js:22
Promise._settlePromises @ vendor.min.2.js:22
(anonymous) @ vendor.min.2.js:20
Async Call
schedule @ vendor.min.2.js:23
util.hasDevTools.Async.settlePromises @ vendor.min.2.js:20
Promise._fulfill @ vendor.min.2.js:22
Promise._resolveCallback @ vendor.min.2.js:22
Promise._settlePromiseFromHandler @ vendor.min.2.js:22
Promise._settlePromise @ vendor.min.2.js:22
Promise._settlePromise0 @ vendor.min.2.js:22
Promise._settlePromises @ vendor.min.2.js:22
(anonymous) @ vendor.min.2.js:20
Async Call
schedule @ vendor.min.2.js:23
util.hasDevTools.Async.settlePromises @ vendor.min.2.js:20
Promise._fulfill @ vendor.min.2.js:22
Promise._resolveCallback @ vendor.min.2.js:22
(anonymous) @ vendor.min.2.js:22
(anonymous) @ vendor.min.2.js:146
Request.callback @ vendor.min.2.js:146
(anonymous) @ vendor.min.2.js:146
Emitter.emit @ vendor.min.2.js:68
xhr.onreadystatechange @ vendor.min.2.js:146
XMLHttpRequest.send (async)
Request.end @ vendor.min.2.js:146
(anonymous) @ vendor.min.2.js:146
Promise._execute @ vendor.min.2.js:21
Promise._resolveFromExecutor @ vendor.min.2.js:22
Promise @ vendor.min.2.js:22
Request.Request.endAsync @ vendor.min.2.js:146
Request.Request.then @ vendor.min.2.js:146
value @ bundle.min.4.js:1562
value @ bundle.min.4.js:1536
(anonymous) @ bundle.min.4.js:1593
(anonymous) @ vendor.min.2.js:145
(anonymous) @ vendor.min.2.js:145
value @ bundle.min.4.js:1579
onClick @ bundle.min.4.js:1579
invokeGuardedCallback @ vendor.min.2.js:37
executeDispatch @ vendor.min.2.js:37
executeDispatchesInOrder @ vendor.min.2.js:37
executeDispatchesAndRelease @ vendor.min.2.js:31
executeDispatchesAndReleaseTopLevel @ vendor.min.2.js:31
forEachAccumulated @ vendor.min.2.js:56
processEventQueue @ vendor.min.2.js:31
runEventQueueInBatch @ vendor.min.2.js:134
handleTopLevel @ vendor.min.2.js:134
handleTopLevelImpl @ vendor.min.2.js:134
perform @ vendor.min.2.js:34
batchedUpdates @ vendor.min.2.js:134
batchedUpdates @ vendor.min.2.js:13
dispatchEvent @ vendor.min.2.js:134
`

**Browser information**
{"name":"Chrome","chrome":true,"version":"63.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 784
Player name: GELight

**Comment by Skedog** [comment] 2018-10-02 18:10
I cannot reproduce this problem. In regards to the 6th step "Clicked on the "Attack" button in the page "Attack missions" to play more matches." - there is no longer an attack button on the "missions" tab from the main page, and the attack button the post attack match screen worked fine for me when using a new account that is unverified.

Closing for now, feel free to re-open if you run into this again.

**Closed by Skedog** 2018-10-02 18:10 UTC
Labels: bug, needs investigation
