### ISSUE TITLE
Login page stops responding due to long-running script on Edge

### ISSUE THREAD

**Issue by mlindgren** [Adam13531/BotLand#171] opened 2018-03-07 22:53 UTC
**Steps to reproduce**
Visit play.bot.land in Edge

**Expected outcome**
Page works

**Actual outcome**
Page hangs due to a long-running script. If you kill the script, the log in button doesn't work.

![botland](https://user-images.githubusercontent.com/945164/37122968-58f44e1e-2217-11e8-8cab-8ed8f22d74b8.png)

**Browser (and version)**
Edge 42.17618.1000.0

**Operating system (and version)**
Windows 10 Insider Preview

**Comment by Skedog** [comment] 2018-10-01 23:54
I cannot reproduce this in Edge Latest (42.17134.1.0) - the login page loads and works as expected.  Closing for now, feel free to re-open if it happens again.

**Closed by Skedog** 2018-10-01 23:54 UTC
Labels: bug, needs investigation
