### ISSUE TITLE
Updating bot code during an attack gives you an"Unsaved Changes" dialog

### ISSUE THREAD

**Issue by DennisRas** [Adam13531/BotLand#7] opened 2017-01-27 19:01 UTC
**Steps to reproduce**
- Start an attack
- Edit and update the code of a bot
- Do either:
  - Commence all phases and win/lose
  - Click cancel

**Expected outcome**
- Going back to news (changes are saved during the attack anyway)

**Actual outcome**
- "Unsaved changes" dialog

**Bowser information**
{"name":"Chrome","chrome":true,"version":"55.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 102
Player name: Liquidor

**Comment by HiDeoo** [comment] 2017-01-27 19:58
Duplicate of #3.

**Comment by Adam13531** [comment] 2017-01-30 17:35
Closing due to duplicate issue.

**Closed by Adam13531** 2017-01-30 17:35 UTC
Labels: duplicate, in-game report
