### ISSUE TITLE
Game crashing in all browsers (white page)

### ISSUE THREAD

**Issue by HiDeoo** [Adam13531/BotLand#196] opened 2018-04-24 23:37 UTC
**Steps to reproduce**

1. Login
2. Edit defense
3. Edit settings from the icon at the top right
4. Toggle master volume checkbox and make sure to leave it as unchecked.
5. Click outside the settings modal to close it.
6. Click Cancel to go back to the homepage.

**Note:** This can also be repro by attacking instead of defending, could be related to editing the master volume setting while a webGL context is present & then navigating away.

**Expected outcome**

Go back to the homepage.

**Actual outcome**

Crash

![screen shot 2018-04-25 at 01 37 18](https://user-images.githubusercontent.com/494699/39219190-35dc7040-4829-11e8-91c3-ac5c427218df.png)

![screen shot 2018-04-25 at 01 41 51](https://user-images.githubusercontent.com/494699/39219298-dd522c5c-4829-11e8-856d-3478640d184c.png)

**Browser information**

{"name":"Safari","safari":true,"version":"11.1","webkit":true,"mac":true,"a":true}

Note: Can reproduce in Chrome & Firefox too

**In-game information**

Player ID: 38
Player name: incognito

**Comment by HiDeoo** [comment] 2018-04-24 23:46
This error should be also used as a testing ground to avoid this kind of behavior. The game should never crash to an empty white page. In the worst case scenario, a full reload or at least a message should be printed out.

In the React land, this should be handled using [Error Boundaries](https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html) introduced in React 16 with at least 1 `componentDidCatch` near the root of the app.

**Comment by Skedog** [comment] 2018-10-02 19:00
As far as I can tell this has been fixed as I cannot reproduce it anymore. Closing for now, feel free to re-open if this happens again.

**Closed by Skedog** 2018-10-02 19:00 UTC
Labels: bug, enhancement
