### ISSUE TITLE
winning game "you made changes prop"

### ISSUE THREAD

**Issue by tehstun** [Adam13531/BotLand#12] opened 2017-01-30 17:47 UTC
**Steps to reproduce**
Create bot while in a fight, win the fight
**Expected outcome**
Exiting without prompt 
**Actual outcome**
after any other fight you will be prompt about changes.
**Bowser information**
{"name":"Chrome","chrome":true,"version":"55.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 21
Player name: digi

**Comment by HiDeoo** [comment] 2017-01-30 17:50
Possible duplicate of / related to #3.

**Comment by Adam13531** [comment] 2017-01-31 18:56
Correct, @HiDeoo, this is indeed a duplicate of #3.

**Closed by Adam13531** 2017-01-31 18:56 UTC
Labels: in-game report
