### ISSUE TITLE
Call to cloneWorkbench when there are blueprint or script modifications

### ISSUE THREAD

**Issue by Pnoexz** [Adam13531/BotLand#213] opened 2018-05-13 01:01 UTC
**Steps to reproduce**
* Edit defense
* Make defense script changes (in Beta and Gamma)
* Select Full Test Mode
* Attack and beat myself in 1 phase
* Play replay
* Click on phase replay progress bar thinking it will bring you to that particular spot
* Play replay again
* Capture GIF with gyazoo (for #214)
* Exit replay. Not sure how I did this, maybe I clicked out of the modal that tells me if I want to save or discard changes, but if I did click any button, it was discard changes.
* Get sent back to after-login page
* Click "Edit Defense"

**Expected outcome**
The usual

**Actual outcome**
![image](https://user-images.githubusercontent.com/3297901/39962743-efb9f772-5647-11e8-9820-788a1cb01ec6.png)

I don't remember exiting the whole "Edit Defense" page, but I might have done it without noticing.

Console output: https://pastebin.com/PpwaA193

**Browser information**
{"name":"Firefox","firefox":true,"version":"59.0","gecko":true,"windows":true,"a":true}

**In-game information**
Client version: 0.2.26
Player ID: 1090
Player name: Pnoexz

**Comment by HiDeoo** [comment] 2018-05-13 08:34
Could be related to the [outcome of 147](https://github.com/Adam13531/BotLand/issues/147#issuecomment-382178004).

**Comment by Pnoexz** [comment] 2018-05-13 16:50
I tried to repro but couldn't do it.. I do have the feeling of "wait, I didn't want to exit Edit Defense", but it did prompt me if I wanted to discard changes.. my guess is somewhere in those pages there is a way to completely exit Edit Defense bypassing the last screen.. the client knows it's in a dirty state but it's not resetting correctly after you click discard changes.. maybe it thinks we are in attack mode? I remember the "there are unsaved changes" had three buttons, while the exit Edit Defense only has two buttons.

I managed to repro the error message in a different way (it didn't mess up my client) but I forgot how to do it. One lead I have, when you are editing your defense, you can attack another player via public link and while you get the "Can't attack player because another attack is in progress" error message, the game actually starts in the game server. I'll continue to investigate.

**Comment by Pnoexz** [comment] 2018-05-17 13:05
Another lead: I did something that triggered that discard changes modal with 3 buttons. I'll try to repro again later, but I think it's related to Blockly reestablishing and old script (I've noticed this before, a deleted/converted script would show up with the "select script or create new" overlay). This happened while streaming: https://www.twitch.tv/videos/262207851?t=00h23m29s

**Comment by Adam13531** [comment] 2019-02-19 19:27
Nearly positive this was a duplicate of #289 (which itself was a duplicate of #272), meaning this will be fixed after version 0.2.89.

**Closed by Adam13531** 2019-02-19 19:27 UTC
Labels: bug

**Comment by Adam13531** [comment] 2019-02-19 19:30
You were first, not second or third. Sorry. 😢
