### ISSUE TITLE
Unable to attack

### ISSUE THREAD

**Issue by Emessen** [Adam13531/BotLand#249] opened 2018-09-05 23:51 UTC
**Steps to reproduce**
I was in the middle of attacking another player. I canceled a bot that I had selected to build. I was then exited to the main screen where it offers me the options of attack or defend. When I press the attack button nothing happens. I can press the defend button and edit my defense. Even when trying to use the tutorial I cannot press the attack button.
**Expected outcome**
The attack button should send me to a screen to attack a specific player.
**Actual outcome**
The attack button seems to not be currently press able.
**Browser information**
{"name":"Firefox","firefox":true,"version":"61.0","gecko":true,"windows":true,"a":true}

**In-game information**
Client version: 0.2.48
Player ID: 2724
Player name: Extalos

**Comment by HiDeoo** [comment] 2018-09-05 23:57
Any error in the console when pressing that button?

**Comment by Pnoexz** [comment] 2018-09-06 11:53
I was just about to report this issue as "Leaving an attack mid-phase breaks the attack button on home screen". There is no error in the console. It's as if the action is not even bound.

**Comment by Emessen** [comment] 2018-09-06 17:16
Yes, or if you finish the attack and want to review it. I just had it
happen again after reviewing an attack then hitting the home button at the
bottom. I then have to leave the game and log back in to fix it.

**Comment by engelju** [comment] 2018-09-07 09:35
Yup, happened to me too.

After completing the tutorial and exiting to the main screen, I wasn't able to start an attack by clicking the "Attack" button there (nothing happens when clicking the button). Editing a defense worked however.

**Comment by Adam13531** [comment] 2018-09-07 17:53
I believe that you're all using Firefox, which is something that I'd never considered as crucial to repros like this, but the problem is that I'm trying to access `.finally` on a native `Promise`. Normally, I use [Bluebird](http://bluebirdjs.com/docs/getting-started.html) for these kinds of things, but I must have messed up somewhere. Will comment when I fix this.

**Comment by Adam13531** [comment] 2018-09-07 18:06
This will be fixed after version 0.2.48. Commit hash: fca0cb701d7a8a4dddea761ae978e7950d1ec5e6

Thanks again for all of the information, everyone! 👍

**Closed by Adam13531** 2018-09-07 18:06 UTC
Labels: bug
