### ISSUE TITLE
Can't access store when inside of Blueprint Editor

### ISSUE THREAD

**Issue by Random101** [Adam13531/BotLand#51] opened 2017-02-27 23:08 UTC
**Steps to reproduce**
Open Blueprint Editor
Click Store

**Expected outcome**
Store opens

**Actual outcome**
Store doesn't open

**Bowser information**
{"name":"Chrome","chrome":true,"version":"56.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 116
Player name: banana (Kappa)

**Comment by HiDeoo** [comment] 2017-02-27 23:16
Duplicate of #40.

**Closed by HiDeoo** 2017-02-27 23:16 UTC
